
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class BookCarForm extends javax.swing.JFrame {
    private Connection connection;
    private int carId;
    private int customerId;
    private String make;
    private String model;
    private Double price;
    /**
     * Creates new form BookCarForm
     */
    public BookCarForm(Connection connection, int customerId, int carId, String make, String model, Double price) {
        this.connection = connection;
        this.customerId = customerId;
        this.carId = carId;
        this.make = make;
        this.model = model;
        this.price = price;
        
        initComponents();
        displayCarDetails();
    }
    
    // Method to dynamically set the car details using setText()
    private void displayCarDetails() {
        carLabel.setText("Booking Car: " + make + " " + model);  // Set the car label using setText
        priceLabel.setText("Price per day: $" + price);  // Set the price label using setText
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        carLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        daysField = new javax.swing.JTextField();
        confirmBookingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(122, 178, 211));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 98, 138));
        jLabel2.setText("Book Car Form");

        carLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        carLabel.setForeground(new java.awt.Color(74, 98, 138));
        carLabel.setText("jLabel1");

        priceLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(74, 98, 138));
        priceLabel.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 98, 138));
        jLabel1.setText("How many days will you take the car?");

        totalPriceLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(74, 98, 138));
        totalPriceLabel.setText("Total Price: $0.00");

        calculateButton.setBackground(new java.awt.Color(122, 178, 211));
        calculateButton.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(74, 98, 138));
        calculateButton.setText("Calculate Total Price");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        daysField.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        daysField.setForeground(new java.awt.Color(74, 98, 138));

        confirmBookingButton.setBackground(new java.awt.Color(122, 178, 211));
        confirmBookingButton.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        confirmBookingButton.setForeground(new java.awt.Color(74, 98, 138));
        confirmBookingButton.setText("Confirm Booking");
        confirmBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daysField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(confirmBookingButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(calculateButton)
                                .addGap(18, 18, 18)
                                .addComponent(totalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(daysField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPriceLabel)
                    .addComponent(calculateButton))
                .addGap(28, 28, 28)
                .addComponent(confirmBookingButton)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        try {
            int days = Integer.parseInt(daysField.getText());  // Get the number of days from the input field
            if (days > 0) {
                double totalPrice = days * price;  // Calculate the total price
                totalPriceLabel.setText("Total Price: $" + String.format("%.2f", totalPrice));  // Set the total price label
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a valid number of days.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number of days.");
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void confirmBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingButtonActionPerformed
        // TODO add your handling code here:
       // Validate that the number of days is entered
    if (daysField.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the number of days.");
        return;
    }

    try {
        // Step 1: Calculate total price based on days
        int days = Integer.parseInt(daysField.getText());
        if (days <= 0) {  // Ensure days is a positive integer
            JOptionPane.showMessageDialog(this, "Please enter a valid number of days.");
            return;
        }
        
        double totalPrice = days * price;  // 'price' is the car's price per day

        // Step 2: Update the car's availability by decrementing the available count and set the booked_by field
        String updateCarQuery = "UPDATE cars SET available = available - 1, booked_by = ? WHERE id = ? AND available > 0";
        try (PreparedStatement updateStmt = connection.prepareStatement(updateCarQuery)) {
            updateStmt.setInt(1, customerId);  // Set customer ID in booked_by column
            updateStmt.setInt(2, carId);  // Use carId to uniquely identify the car
            int rowsAffected = updateStmt.executeUpdate();
            
            if (rowsAffected == 0) {  // If no rows were updated, the car is not available
                JOptionPane.showMessageDialog(this, "This car is no longer available.");
                return;
            }
        }

        // Step 3: Update the customer's total_price in the 'customers' table
        String updateCustomerQuery = "UPDATE customers SET total_price = total_price + ? WHERE id = ?";
        try (PreparedStatement updateStmt = connection.prepareStatement(updateCustomerQuery)) {
            updateStmt.setDouble(1, totalPrice);  // Increment the customer's total price by the booking's total price
            updateStmt.setInt(2, customerId);  // Use customerId to identify the customer
            updateStmt.executeUpdate();
        }

        // Step 4: Show success message and close the booking form
        JOptionPane.showMessageDialog(this, "Car booked successfully! Total price: $" + String.format("%.2f", totalPrice));
        this.dispose();  // Close the window after booking

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number of days.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "An error occurred while booking the car.", "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_confirmBookingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new BookCarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel carLabel;
    private javax.swing.JButton confirmBookingButton;
    private javax.swing.JTextField daysField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
